version: '{build}'

image: Visual Studio 2017 RC

configuration: Release

platform: Any CPU

build_script:

- ps: >-
    $currentPath = Get-Location

    dotnet restore

    dotnet build -c $env:CONFIGURATION --no-incremental

    Get-ChildItem .\tests\ -Directory | %{ cd $_.FullName; dotnet test }

    Set-Location $currentPath

    Get-ChildItem .\src\ -Directory | %{ cd $_.FullName; dotnet pack -c $env:CONFIGURATION --no-build }

test: off

artifacts:

- path: '**\*.nupkg'
